[tool.poetry]
authors = ["Benjamin Sparks <benjamin.sparks@protonmail.com>"]
description = "Collection of scripts for evaluating performance of type annotation processes for Python"
license = "MIT"
name = "scripts"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
click = "^8.1.3"
libcst = {git = "git@github.com:multidim-typeinf4py/LibCST.git", branch = "feature/type-collector"}
pandas = "=1.4.3"
pandera = {extras = ["mypy"], version = "^0.13.4"}

[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"
mypy = "^0.991"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pandas-stubs = "<=1.4.3"

[tool.mypy]
plugins = ["pandera.mypy"]
exclude = ["x.py"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
